spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mpdweb
    username: postgres
    password: qwerty

mpd:
  host: localhost
  port: 6600

status:
  polling:
    interval: 1000 # milliseconds
